name: Manually generate documentation

on:
  workflow_dispatch

jobs:
  generate-documentation:
    name: Generate documentation for release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate documentation and upload
        uses: docker://ponylang/library-documentation-action:release
        with:
          site_url: "https://nogginly.github.io/termax.pony/"
          library_name: "termax"
          docs_build_dir: "build/termax-docs"
          git_user_name: "nogginly"
          git_user_email: "nogginly@icloud.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
